# Generated by Django 5.1.4 on 2025-04-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_category_alter_recipe_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Slug',
            new_name='slug',
        ),
    ]
